# VULCAN
## IMPORTING MODULES

In [13]:
import pandas as pd
import numpy as np

## LOADING RAW CSVs

In [14]:
complaints = pd.read_csv('complaints.csv')
customers = pd.read_csv('customers.csv')
service = pd.read_csv('service_records.csv')
vehicles = pd.read_csv('vehicles.csv')

print(complaints.shape, customers.shape, service.shape, vehicles.shape)

(350, 6) (415, 6) (2210, 7) (550, 8)

## INSPECTING THE CSVs

### complaints.csv

In [15]:
complaints.head()

,complaint_id,vehicle_id,complaint_date,category,status,resolution_days
0,CMP0001,V0137,2025-04-19,Battery Drain,Escalated,3.0
1,CMP0002,V0062,2026-03-29,Noise/Vibration,open,0.0
2,CMP0003,V0273,2026-08-06,Billing Issue,Resolved,0.0
3,CMP0004,V0328,2025-02-06,Poor Staff Behaviour,Resolved,14.0
4,CMP0005,V0194,2025-04-09,Poor Staff Behaviour,Resolved,3.0

In [16]:
complaints.describe()

       resolution_days
count       287.000000
mean          5.034843
std           4.753229
min           0.000000
25%           2.000000
50%           3.000000
75%           8.000000
max          14.000000

In [17]:
complaints.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   complaint_id     350 non-null    object
 1   vehicle_id       350 non-null    object
 2   complaint_date   350 non-null    object
 3   category         342 non-null    object
 4   status           350 non-null    object
 5   resolution_days  287 non-null    float64
dtypes: float64(1), object(5)
memory usage: 16.5+ KB

In [18]:
complaints.isna().sum()

complaint_id        0
vehicle_id          0
complaint_date      0
category            8
status              0
resolution_days    63
dtype: int64

In [19]:
complaints['category'].value_counts()

category
Billing Issue           44
Poor Staff Behaviour    38
Charging Issue          38
Delayed Service         38
Battery Drain           37
Part Unavailability     36
Brake Issue             33
AC Not Cooling          31
Noise/Vibration         25
Software Glitch         22
Name: count, dtype: int64

In [20]:
complaints['status'].value_counts()

status
Resolved     64
Open         63
RESOLVED     61
Escalated    58
open         58
Closed       46
Name: count, dtype: int64

There are same categories that are being treated different just because they are written differently. We have to resolve this issue.

In [21]:
complaints_clean = complaints.copy()

complaints_clean['status'] = complaints['status'].str.strip().str.capitalize()

In [22]:
complaints_clean['status'].value_counts()

status
Resolved     125
Open         121
Escalated     58
Closed        46
Name: count, dtype: int64

Now, we have the 4 standard status - Resolved, Open, Escalated, Closed

**Hypothesis-1**

From this data, we can make a hypothesis that the missing values in resolution_days may be missing because those complaints have not yet been resolved — meaning complaints with an unresolved status such as Open (including open) may have resolution_days = NaN.

In [25]:
complaints_clean[complaints_clean['resolution_days'].isna()]['status'].value_counts()

status
Open         25
Resolved     23
Escalated     9
Closed        6
Name: count, dtype: int64

The missing values contains the values from all the categories, so we reject this hypothesis.

Now lets move on to the next investigation. We want to know if every complaint ID is unique.

In [26]:
complaints_clean['complaint_id'].duplicated().sum()

np.int64(0)

Every complaint_id is unique. So there is no problem in this. 

Lets check the